### ISSUE TITLE
airline data not found

### ISSUE THREAD

**Issue by nandaloo** [lumen-org/modelbase#59]
when executing create_pymc3_testmodels.py:

FileNotFoundError: [Errno 2] File b'/home/luca_ph/Documents/projects/graphical_models/code/models_ppl/airlineDelayDataProcessed.csv' does not exist: b'/home/luca_ph/Documents/projects/graphical_models/code/models_ppl/airlineDelayDataProcessed.csv'

**Comment by jong42** [comment]
airline data is now in tests directory, see commit 4341659
